workspace = { members = [ "src/contest403","src/p2701_2800", "src/p3001_3100"] }
[package]
name = "leetcode-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
